### ISSUE TITLE
Nelze smazat diagram v OG

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/sgov-assembly-line#178]
# Popis problému
Chci v OG smazat diagram. Po stisku tlačítka potvrdit se nic nestane, v konzoli vyskočí error.
```
FunctionDiagram.ts:16 Uncaught TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at gm (FunctionDiagram.ts:16:8)
    at n.value (ModalRemoveDiagram.tsx:20:7)
    at onSubmit (ModalRemoveDiagram.tsx:55:20)
    at Object.He (react-dom.production.min.js:52:317)
    at Ye (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Tr (react-dom.production.min.js:100:68)
    at jr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
```

![mazání diagramu](https://github.com/datagov-cz/sgov-assembly-line/assets/718827/d67f2cf6-5dec-44f8-b771-fffd8a48cdef)

# Závažnost problému
2. je to vážný problém,

**Comment by MichalMed** [comment]
nepodailo se mi zreplikovat (diagram, is pojmy, normálně smažu)

**Comment by bindeali** [comment]
> nepodailo se mi zreplikovat (diagram, is pojmy, normálně smažu)

Problém se vyskytuje, když se pokusíš smazat poslední diagram.

**Comment by bindeali** [comment]
Mělo by být vyřešeno na PROD, prosím o kontrolu.

**Comment by jakubklimek** [comment]
Ano, už to funguje.
